# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip:"192.168.1.2"
  config.vm.hostname = "control-node"
  #config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provider :virtualbox do |v|
    v.name = "control-node"  
  config.vm.provision "shell", path: "provisioner/provision.sh"
  end
end
